# Generated by Django 4.2.19 on 2025-05-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_created_at_task_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
